# [CoE202] note 01b. Import numpy

- Class Date : 2021.03.11.
- Office Hour : TBA
- If you have any questions, upload on KLMS Q&A board, or ask directly at the TA office hours (Zoom).

## 1. Numpy array
Throughout this course, we will be using Numpy a lot.
In this example, let's familiarize ourselves with Numpy array.

In [1]:
# this is just an annotation
import numpy as np # this is for importing numpy library (and we will use abbreviation np for that)

In [2]:
# create an integer array from 0 to 14
my_array = np.arange(15) # create a numpy array (my_array)
print(my_array) # print the array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
my_array.shape # show the shape of the array  

(15,)

In [4]:
my_array = my_array.reshape(3, 5) # reshape my_array as 3x5
print(my_array) # print the (reshaped) array
my_array.shape  # show the shape of the array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [5]:
my_array2 = np.array([2,3,4.1]) # create a numpy array (my_array2)
print(my_array2) #print my_array2
my_array2.dtype  # show data type of my_array2

[2.  3.  4.1]


dtype('float64')

In [6]:
my_array3 = np.zeros((3,4)) # create a numpy array filled with zeros (my_array3)
print(my_array3)            # print my_array3

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
my_array3[1,2]=1 
print(my_array3)

[[0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
